### ISSUE TITLE
Shipping Costs 

### ISSUE THREAD

**Issue by virgiltu** [bumbummen99/LaravelShoppingcart#105]
I love this package but the shipping is a nightmare to deal with. If you add it as a cart item and the customer deiced to do more sopping you now show more cart items than the user has in count. Can you please add it just like there is discounts. If anybody else calculates it different than o well, but for most uses this would be ideal as costs are fixed. Even if you have a cost per item you still end up adding them up at the end.

**Comment by bumbummen99** [comment]
Sorry if i misunderstand the issue but do you mean fixed discounts? You should be able to do that quite easily by creating your own Calculator:
https://github.com/bumbummen99/LaravelShoppingcart/blob/master/src/Contracts/Calculator.php
https://github.com/bumbummen99/LaravelShoppingcart/blob/master/src/Calculation/DefaultCalculator.php
https://github.com/bumbummen99/LaravelShoppingcart/blob/master/src/Config/cart.php

If so and you have an own calculator in mind we would be happy for an PR since i have seen this being requested quite some times 👍

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….
