### ISSUE TITLE
could you plese add paginate for items in cart

### ISSUE THREAD

**Issue by usaikoo** [bumbummen99/LaravelShoppingcart#117]
Please how to get the items in carts with the pagination. I could not try for it.

**Comment by bumbummen99** [comment]
The cart, internally, just uses a Collection so you you can only use the following methods on it:
https://laravel.com/docs/8.x/collections

It also stores the content as serialized string on the cart table. This would have to be split into an i.e. positions table and internally only a query be used instead of a collection. That would also require to change a lot of the cart functionality. Id be open for a PR for that 👍

**Comment by usaikoo** [comment]
Thank you for your reply. I will try as you suggested. I will closed the my
issue for now. Thank you again.
Best regards
