### ISSUE TITLE
Why not associate the whole model instead of the class name?

### ISSUE THREAD

**Issue by aneeskhan47** [bumbummen99/LaravelShoppingcart#129]
Hi,

i'm thinking why this package don't associate the model (collection) retrieved by dev (e.g doing $model = Model::find($id)) instead of associating the model namespace (e.g App\Models\Course), so when dev do the Cart::content() loop and access the model property which hits the database query...

IMPORTANT: Everytime you call $cartItem->model it hit database query each time

currently i'm doing this my own solution:
![image](https://user-images.githubusercontent.com/30714223/127344387-84bc6b94-6710-44c5-b0a7-8a935f8f09e8.png)

![image](https://user-images.githubusercontent.com/30714223/127344785-beeef263-9767-47bc-878c-11cafe59d91c.png)

@bumbummen99 what do you think?

sorry for the poor english though

**Comment by aneeskhan47** [comment]
@bumbummen99

**Comment by bumbummen99** [comment]
A main problem of this package is that the cart is saved as an collection, so there always will be hits for the model on the DB. We do have to save the FQCN since we need to know what model it is associated to. When loading the cart (from db), there is no instance of the model since it is stored as an collection (**what breaks 1NF**), you resolve it when you call the property.
One **big** improvement to this package as a whole would be to use [polymorphic relationships](https://laravel.com/docs/8.x/eloquent-relationships#polymorphic-relationships), that way the CartItems can be stored and also be updated seperately to the cart while being able to be eager loaded, paginated, chunked and so on. It would have some drawbacks to a session based system tought that is something that should build upon it or be solved completely out of the package iMo.

**Comment by aneeskhan47** [comment]
@bumbummen99 so what disadvantages i have of what i'm doing currently up in the screenshots?

**Comment by bumbummen99** [comment]
> 
> 
> @bumbummen99 so what disadvantages i have of what i'm doing currently up in the screenshots?

The most obvious disadvantage would be that you do not have a model anymore but an Collection of an array of its data, so you can not use methods of the model object as it is not an instance of the model anymore. Also, you then will have to manually update the CartItem when the model changes (if that is desired by your app). In extension to that you will bloat your CartItem and therefore your cart table with more, possibly uneccesary, data (every attribute instead of just the required ones).

Imo it would be better to, in that case too, move CartItems into their own table and relate them to the cart and model, that way model can be resolved by eager loading in one query and you have an actual model instead of just it's data.
