### ISSUE TITLE
Please supply a valid weight. in laravel 6.2

### ISSUE THREAD

**Issue by luneeruhanee** [bumbummen99/LaravelShoppingcart#37]
this is in CartController

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use Cart;

class CartController extends Controller
{
    public function addToCart($id)
    {
    	$product = Product::find($id);
    	
    	Cart::add($id, $product->title,1, $product->price,['size'=>'s','image'=>$product->image]);

    	return back()->withInfo('Added product to cart');
    }
}
```

this in web.php

```
Route::get('/', function () {
	$cartItems = Cart::content();
	$categories = App\Category::all();
	$products = App\Product::paginate(8);
    return view('welcome', compact('products','categories','cartItems'));
});
Route::get('/addToCart/{id}', 'CartController@addToCart')-> name('addToCart');
```

this is the button

`<a href="{{route('addToCart', $product->id)}}" class="btn btn-primary pull-right btn-sm">Add to Cart</a>`

please help

**Comment by bumbummen99** [comment]
The problem is the signature of the method:
https://github.com/bumbummen99/LaravelShoppingcart/blob/fe5fe942c295006b2377a6d471d9d77db5ac7c80/src/Cart.php#L113

In your code you pass 5 parameters to the `add()` method, therefore the array meant as options will be passed as weight instead of the default 0 weight. You will simply have to pass an additional 0 before the array if you don't need the weight.

**Comment by luneeruhanee** [comment]
thanks

**Comment by bumbummen99** [comment]
You are welcome 👍
