### ISSUE TITLE
Is it possible to load the associated models?

### ISSUE THREAD

**Issue by 4unkur** [bumbummen99/LaravelShoppingcart#41]
As it was shown in the docs:
```
Cart::add($product, 1, ['size' => 'large']);
```
I have used similar approach to add models to cart.
Once I get the content out of the cart by doing:
```
Cart::content();
```
I can see the collection of CartItem models. 

Question: is it possible to somehow load the related model?
I tried to modify the collection, but once it's casted to JSON, I think it calls CartItems toArray method or something. small_image_url attribute is not present in JSON:
```
$items = cart()->content()->transform(function ($item) {
    $product = Product::find($item->id);
    $item->small_image_url = $product->getImageUrl(Product::CONVERSION_SMALL);

    return $item;
});
```

**Comment by bumbummen99** [comment]
If i understand correctly what you are trying to do this might help or be the solution :+1: :

https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/Cart.php#L718
So on adding/creating a `CartItem` from a `Buyable`model, the package will automatically associate the model to the CartItem. The CartItem will then hold it in it's `associatedModel`-member. In order to access this (model) you can use the `model` getter:
https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/CartItem.php#L380

What might also be interesting or helpful in this case are the following methods.

https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/Cart.php#L472
This enables you to manually assoicate a CartItem by it's row id.

https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/CartItem.php#L312
Practically the same but on the CartItem instance itself.

Note that you can also access the models FQCN by using the CartItems `modelFQCN` getter.

**Comment by 4unkur** [comment]
Hello @bumbummen99 

First of all, thank you for bringing this package again back to life and for quick response.

This will work excellent if I will show my cart items via blade, but in my case cart items are rendered in Vue so I needed to pass JSON casted items. When passing to Vue, CartItem is casted to JSON: https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/CartItem.php#L480 and as you can see there are only limited fields.

Eventually, I used Eloquent Resource for CartItem (I called it CartItemResource) where I loaded my model:
```php
class CartItemResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'rowId'    => $this->rowId,
            'id'       => $this->id,
            'name'     => $this->name,
            'qty'      => $this->qty,
            'price'    => $this->price,
            'weight'   => $this->weight,
            'options'  => $this->options->toArray(),
            'discount' => $this->discount,
            'tax'      => $this->tax,
            'subtotal' => $this->subtotal,
            'resource' => new ProductResource($this->model),
        ];
    }
}
```

and usage:

```php
            return CartItemResource::collection(cart()->content());
```

Thanks.

**Comment by bumbummen99** [comment]
@4unkur Great way of solving it but i am wondering if we should make the CartItem model configurable so that the user can extend it or give the option to include the model, if associated, in the Json output.
