### ISSUE TITLE
Cart total rounding issue 

### ISSUE THREAD

**Issue by Sartoric** [bumbummen99/LaravelShoppingcart#58]
I've seen that there is a rounding issue on the cart total 

(discount,subtotal,taxes,total)
![rounding](https://user-images.githubusercontent.com/6607379/72162628-997d0200-33c2-11ea-9609-5fb5cefecec7.png)

and in fact the __get() is not rounding the result of the internal calculation (adding more decimals to the results). 
This lead to a potential rounding issue in the total.

Digging a bit I've found this in Crinsane version 

https://github.com/Crinsane/LaravelShoppingcart/issues/344
and this PR 
https://github.com/hardevine/LaravelShoppingcart/pull/5/commits/3e4f5a14ba58bd7cee950de3d91ea10960c2724f

I guess it should be done something similar here using **round** as some values are used for other calculation

**Comment by Sartoric** [comment]
I'm just thinking a bit about this issues as we are managing prices so every cent matter. 
So probably rounding in the __get() is not the best solution.

**Comment by bumbummen99** [comment]
I am also for using `round()` over `number_format()` in this case since it will not change the data type of the returned value (`number_format()` does return string while `round()` is float). I am kinda worried why 
https://github.com/bumbummen99/LaravelShoppingcart/blob/3abb164dddcbd62b8694d508861c204029071486/tests/CartTest.php#L1052
did not pick up on this behaviour as it should verify exactly that given it's name.

**Comment by Sartoric** [comment]
Yep, I was re-thinking the solution due to the fact that the test fail if the round() is used*
Unfortunately that test check just a single value (total) while the issue is noticeable when you check if the rounded Cart:total is equal to rounded Cart:subtotal + rounded Cart:tax.
That's the test I was working on.

*if you round (in the __get() function) with a precision equal to (at least) the precision of the price, it works
eg. price = 10.004 , round(<value>, 3)

**Comment by Sartoric** [comment]
I did some test earlier to check the test result. 
Here it it is (just for sake of knowledge) 😁 

rounding by 2 in the __get()

price | qty | taxes | priceTax | total (x qty) |  
-- | -- | -- | -- | -- | --
10,004 | 2 | 2,10084 | 12,10484 | 24,20968 | **24,21**
  | rounded tax→ | 2,1 | 12,104 |   |  
  |   | rounded priceTax→ | 12,1 | **24,2** |  

rounding by 3 

price | qty | taxes | priceTax | total (x qty) |  
-- | -- | -- | -- | -- | --
10,004 | 2 | 2,10084 | 12,10484 | 24,20968 | 24,21
  | rounded result→ | 2,101 | 12,105 |   |  
  |   | rounded result→ | 12,105 | 24,21 |

**Comment by bumbummen99** [comment]
Ok, reading a bit into the matter i think there are basically two ways to go here:

We can round in-between internal calculation or we can not. It is only important that we then stick to this value for further calculations.

Also we should strictly split public accessible values meant for that and those for internal calculation. If we do not round in-between calculations it is possible that the displayed values don't add up but the raw ones do as far as i understood. I am yet not quite sure if there is a solution that allows us to display values that also add up (i.e. rounding in between) in the end without loosing the  precision of calculation with raw values. If we would do that we would have to calculate the win/loss caused by this rounding to mention it.

Also i noticed that we should include an rounding option to the package to allow for:
- Round normal
- Round down / floor
as this is an important part of the calculation for a business. As far as i have read the general international legal consensus is that you can not round up as it is overcharging but you can round down to show you good business practice or stick to normal rounding.

**Comment by Sartoric** [comment]
Agree

Basically the 2 way to manage totals are: 
- Round per item/unit `round(discounted price+tax)`
- Round per row `round((discounted price*qty)+(tax_x_qty))`

The second method seems to be a little bit more precise
atm it looks like we're using a mixed mode (subtotal and total) and rounding it's always done at the end.

I'm just testing this two 
`            case 'totalperunit':
                return round($this->priceTax, $decimals)*$this->qty;
            case 'totalperrow':
                return round($this->subtotal + $this->taxTotal, $decimals);`

**Comment by Sartoric** [comment]
Probably I've sorted it out (without the round up/down option atm)
I'll try to PR changes asap with tests

**Comment by Sartoric** [comment]
I've sent the PR but some more consideration are needed

**CartItem->price** and **CartItem->discount** are left unrounded 

If the user can set a different amount of decimal to be shown in the formatted output the issue can popup.
eg. 
test : it_use_correctly_rounded_values_for_totals_and_cart_summary()
calculation done with 5 decimals but only 2 shown  	-> can be wrong
calculation done with 2 decimals and only 2 shown  -> OK

We could 
- stick to the default/config decimal precision and avoid output formatting for decimals. That's what happen in most (all?) ecommerce
- or we should find a way to set it for every calculation. This will keep it flexible (for whatever use) put potentially "bugged"  (more investigation needed)

I guess that something should be added to the readme to warn about this potential issue, but not sure what :)

**Comment by bumbummen99** [comment]
@Sartoric The PR looks good so far.

Yes, a notice in the readme is never wrong 👍 We should explain the issue and the resolution approach there in a short manner. Also i think we should go for the first approach yet as we can still make it flexible later on as it would be required (but i currently can not make up any benifit of it).

I would only display the discountTotal for a single Product / CartItem so i think leaving the disount unrounded is ok, allrought we could add a accessor (not to be used for calculation) so the round/number_format has not to be copied over and over. That would also only ever be an estimate since the raw value *can* differ so that has to be made clear to the user. 
In extend to that i think we can leave price unrounded since if the user does use more than 2 decimals as a value (like in huge bulk orders or something like that) they are propably going to expect those more decimals and will handle them on their way.

**Comment by Sartoric** [comment]
> @Sartoric The PR looks good so far.
> 
> Yes, a notice in the readme is never wrong 👍 We should explain the issue and the resolution approach there in a short manner.

I'll write down a couple of lines, just saying the strategy used (per row) some notes about the ProductTotal() method added and some capital bold warning :grin: about formatting the output.
 
>Also i think we should go for the first approach yet as we can still make it flexible later on as it would be required (but i currently can not make up any benifit of it).

Totally Agree. 
Would you keep the possibility to round the output for format purpose (at least for now) ? 
 
> I would only display the discountTotal for a single Product / CartItem so i think leaving the disount unrounded is ok, allrought we could add a accessor (not to be used for calculation) so the round/number_format has not to be copied over and over. That would also only ever be an estimate since the raw value _can_ differ so that has to be made clear to the user.

If you agree, let's open a new enhancement request for this one so we can keep track of it and manage it separately.

> In extend to that i think we can leave price unrounded since if the user does use more than 2 decimals as a value (like in huge bulk orders or something like that) they are propably going to expect those more decimals and will handle them on their way.

Yep. I'm keeping it unrounded as I need it 😁  for the cart summary, to show price per unit for a ironware wholesaler (that's why I found the rounding bug 👿 )

**Comment by Sartoric** [comment]
Take a look 
#61

**Comment by bumbummen99** [comment]
No, i think it is fine (i think i would have made the heading red color :laughing:). At last it's an important topic/problem to remember in an eCommerce system i think.

**Comment by Sartoric** [comment]
@bumbummen99 
Are you going to merge and deploy the PR  ?

**Comment by bumbummen99** [comment]
Yeah sorry for the long wait, i have been in a rush lately  >.> I have tagged it under 2.8.9 :+1:

**Comment by Sartoric** [comment]
@bumbummen99 
No problem :D I was wondering if we had something else to do
