### ISSUE TITLE
How to use cart in appserviceprovider

### ISSUE THREAD

**Issue by amasahara** [bumbummen99/LaravelShoppingcart#62]
i try to add some data into appserviceprovider to share data into header for showing quick data but it not get data, only when i go to detail page it get my counting data

my AppServiceProvider:
public function boot()
    {
$data['items'] = Cart::content();
        $data['cart_total'] = 0;
        $data['promotion_total'] = 0;
        $data['coupons_total'] = 0;

        foreach(Cart::content() as $item){
            $data['promotion_total'] += $item->price*$item->qty*$item->options->promotion/100;
            $data['cart_total'] += $item->price*$item->qty;

            if($item->discountRate > 0){
                $data['coupons_total'] += ($item->price*$item->qty - $item->price*$item->qty*$item->options->promotion/100)*$item->discountRate/100;
            } else {
                $data['coupons_total'] += $item->options->coupons_value;
            }
        }

        $data['pay_total'] = (double)$data['cart_total']-(double)$data['promotion_total']-(double)$data['coupons_total'];
view()->share($data);
}

please help me know which way i wrong.

**Comment by bumbummen99** [comment]
Sorry if i have to say but i do not really understand what exactly you are trying to do or what exactly is not working with your code. If there is no Exception but unexpected values i suggest using xDebug and debug the related code step by step while checking the variable values.

Since you say you are missing something that you get in the detail page of your application, do you load the cart instance before the code is being executed?

**Comment by amasahara** [comment]
thanks for reply i try another way and i has been do it
i use View::composer('*', function ($view) { 
and put all content into it and it work fine.
i need set cart as global value
