### ISSUE TITLE
Ability to customise how the cart handles pricing?

### ISSUE THREAD

**Issue by marbuser** [bumbummen99/LaravelShoppingcart#63]
So is it somehow possible we can make it so that the cart can take prices in cents rather than decimal? Generally speaking it's better practice to keep it as cents in the DB. Or at minimum add an option for those who want it so that others who don't want to use it don't have to.

As a side question as well; with the buyable interface is it possible we can let the price be it's own thing?

I'm making a SaaS application where products can have multiple prices, and I'm storing them via ManyToMany with the product. It would nice to be able to pass in the Price model along with the product on `Cart::add`.

Not sure if these are already possible but from my testing it doesn't seem like it!

**Comment by bumbummen99** [comment]
So if i understand this correctly you do want to store the price as an integer, right? This package does not make any assumptions on how you store your price. If you create your CartItem with an numeric type you are good to go. You could just pass it your cents as a whole number but you will also have to remember to view it as cents then and also configure the seperators and decimals correctly.
Alltought keep in mind, internally, this package does use floatval and number format. If you are asking because of the precision of the calculations, there is discussion on the topic over here #62.

Also there are many ways to pass the price. It is just important that you pass the desired price to the package. If you call `add()` then you have to pass it there. Using the `Buyable` interface you can implement it's `getBuyablePrice` method to get the correct price in your application. But remember, the `Buyable` contract will only work if you pass the implementing model as the parameter.

**Comment by marbuser** [comment]
@bumbummen99 
Thanks for the quick reply.

Regarding the first part, yeah I wanted to store it as an integer of cents to not screw up precision. So 14.99 would become 1499. My only concern was I was not sure how this would impact functions like; `tax`, `total`, `subtotal`, etc... + I'm not sure if there is a way for me to edit it in a way so that these still RETURN a decimal for displaying on the page. Just want to use cents internally so precision wise there are no issues and feels more reliable.

**Comment by Sartoric** [comment]
@marbuser 
Out of curiosity
If you have 134 cents as the price and you calculate, let's say, a 20% tax (26,8) how you'll manage those 8 "decimal" of cents ? I mean, what should be the correct price ?
