### ISSUE TITLE
Class 'App\Http\Controllers\Cart' not found

### ISSUE THREAD

**Issue by spandan114** [bumbummen99/LaravelShoppingcart#77]
Cart::add($request->id,$request->name,$request->quentity, $request->price)->associate('App\product');

**Comment by spandan114** [comment]
Cart::add($request->id,$request->name,$request->quentity, $request->price)->associate('App\product');

whats the problem

**Comment by bumbummen99** [comment]
Hey, sorry for the late response. 

Composer should alias the Facade of the package:
https://github.com/bumbummen99/LaravelShoppingcart/blob/86d25d9fb8f7aa062d1e444b1b4eea7e751c30e2/composer.json#L48

I assume your code is `Cart::` instead of `\Cart`? Without the leading slash you tell the autoloader to search relative to your Controllers namespace.
