### ISSUE TITLE
Having trouble understanding the "flow"

### ISSUE THREAD

**Issue by nexxai** [bumbummen99/LaravelShoppingcart#79]
Ok so this is probably old hat for most of you but this is the first time I'm building a site with a cart functionality in it, and I'm having trouble wrapping my brain around a few super basic things and I feel like I'm missing a critical piece of knowledge that is going to make this all come together.  

To begin, I've written some very basic logic to generate a cartId like this:

```php
public function get_cartId()
{
    if (Auth::guard('api')->user()) {
        $cartId = Auth::guard('api')->user()->id;
    } else {
        $cartId = md5(random_bytes(4));
    }

    return $cartId;
}
```

The idea is that if you're logged in, the cart should be attached to your actual user ID; if you are not logged in, the cartId will just be a random MD5.  This allows new users to browse and add items to a cart without actually needing a login before hand.

Now here's where I already start to get lost.  If I'm reading the documentation correctly, I have to call the `Cart::instance($cartId);` before I do anything else.  Then let's add an item to the cart, so I do `Cart::add([...]);` Next, if I'm reading the documentation correctly, if I want to persist/store the cart to the DB, I need to call `Cart::store($cartId);` within my controller after I've performed the  action.  So at this point, my controller should look something like this:

```php
public function store(CartRequest $request)
{
    $cartId = CartService::get_cartId($request);

    Cart::instance($cartId);

    Cart::add(
        (int) $request->product_id,
        (string) 'Example description',
        (int) $request->quantity,
        (int) 10,
        0
    );

    Cart::store($cartId);

    return response('Item added to cart', 202)->cookie('cart_id', $cartId);
}
```

But now, if the person tries to add a second item to their cart, they get an error saying the cart with that cartId already exists, because apparently the store() method doesn't do an updateOrCreate() behind the scenes(????).  So now I have to add a `Cart::restore($cartId);` before the ::instance(); because it removes the entry from the DB temporarily until the ::store(); puts it back. The destroy() controller method needs an equivalent number of calls, substituting the ::remove() for the ::add().

Having 4 Cart:: calls in a single controller method seems excessive, and I feel like I'm missing some foundational piece of "cart-making" and am doing way too much to accomplish a relatively simple task.

Can someone help clear up whether what I'm doing is correct or not, and assuming that I'm doing it wrong, can you even just give some super basic pseudocode of what I *should* be doing?

**Comment by nexxai** [comment]
I've also just discovered a flaw in my process that really makes me think I'm missing a core piece of the puzzle: a race-condition that results in the cart being completely deleted.

If a user hits the API multiple times in too quick succession, the ::restore() and ::store() methods that are being called nearly simultaneously can interfere with/overwrite each other, nuking the person's cart altogether.

Pseudocode:
```
API-request-1 -> API
API(1) -> ::restore($cart)
API-request-2 -> API
API(1) -> <cart restored from DB; loaded into memory>
API(2) -> ::restore($cart)
API(1) -> ::instance($cart)
API(2) -> <cart does not exist in DB; no data returned>
API(2) -> <no data to process> ::instance($cart)
API(1) -> <stores correct cart to DB> ::store($cart)
API(2) -> <cart is empty, empty cart written to DB> ::store($cart)
```

Since there isn't a way to batch all of the calls in a single DB transaction, there's no way to lock or even prevent the cart from accidentally being over written from a second thread.  I'm assuming this has already been considered, meaning that I'm missing a step.

Can someone help me understand where my logic is flawed?

**Comment by bumbummen99** [comment]
Sorry for the late answer but i do not have as much time as i used to :/
You can find an example project over here https://github.com/bumbummen99/LaravelShoppingcartDemo.

Generally the cart is stored in the Session (problematic with API since there is none by design) and with some modification to the [logout process](https://github.com/bumbummen99/LaravelShoppingcartDemo/blob/b7af949ca22a35f3eccc25f4a0ac7da19c868c0b/app/Http/Controllers/Auth/LoginController.php#L49) you can also persist it on logout. Usually that is all you have to do really. I think this should also be added to the Readme.

Also [there is a good explanation ](https://github.com/bumbummen99/LaravelShoppingcart/issues/44)by @Sartoric on the restore functionality, i did the same back then for a customer project by using Listeners on the [Login](https://laravel.com/api/7.x/Illuminate/Auth/Events/Login.html) / [Logout ](https://laravel.com/api/7.x/Illuminate/Auth/Events/Logout.html)event (My users use the InstanceIdentifier trait so they are their own identifier for their main cart).
```php
class RestoreCartOnLogin
{
    /**
     * Restore the Cart on login
     *
     * @return void
     */
    public function handle( Login $login )
    {
        if ($login->user) {
            Cart::restore($login->user);
        }
    }
}
```
```php
class StoreCartOnLogout
{
    /**
     * Store cart on logout
     *
     * @return void
     */
    public function handle( Logout $event )
    {
        if ($event->user && Cart::instance($event->user)->count() > 0) {
            Cart::store($event->user);
        }
    }
}
```
This race condition has not been considered yet but i am not quite sure right now on what to do about it. Generally i think the saving/loading functionality does need a rewrite to also support session-less scenarios such as API projects and reduce the complexity (Laravel handles Sessions differently on Logout now, effectively requiring the mentioned changes to the logout proecss).

**Comment by nexxai** [comment]
I don't know if there would be a better way without wrapping the entire restore/[add/update/delete/etc.]/store in a single "atomic" DB transaction as described here: https://laravel.com/docs/7.x/database#database-transactions  (I know it's not *actually* atomic, but it functions sort of like that).

**Comment by bumbummen99** [comment]
Generally i was thinking of making the cart completely db based so operations to the same cart do not interfere (Operations to the same CartItem could). This would also allow to use this package with APIs easily but we will still need Session support for the public cart, since guests have no account there is only their session to store the cart/identifier (i'd rather store the cart in session for guests 
to keep the db clean for guests).

In my opinion the general flow of loading it into the session and storing/deleting in the db is overcomplicating things and i am not really happy with it since it only makes sense from a browser point of view.

**Comment by Sartoric** [comment]
Basically api end points could in fact substitute "session" methods and everything must be obviously kept in db
Guest carts could be managed using a unique (reusable?) hash as a separate end point and maybe separate table

for some inspiration 😁 
https://devdocs.magento.com/guides/v2.3/rest/list.html#quote
https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-quote.html

**Comment by Sartoric** [comment]
@nexxai just a note that maybe can help you atm 
> So now I have to add a Cart::restore($cartId); before the ::instance(); because it removes the entry from the DB temporarily until the ::store(); puts it back. 


You can do something like this 

```
    public function updateCartDb($cartId)
    {
        try {
            DB::transaction(function () use ($cartId) {
                // remove the old cart from db
                Cart::erase($cartId);
                // store the new cart if not empty
                if (Cart::count()>0) {
                    Cart::store($cartId);
                }
            });
        } catch (Exception $err) {
        }
    }
```

this is the method I fire on each session cart event (eg cart.added)
of course I'm working with browser and not with api

**Comment by nexxai** [comment]
My bigger problem is that restore() *removes* the entire cart from the DB temporarily, which is completely unnecessary.  Instead of removing the entry, it should just read it from the DB, and then instead of store() just assuming it's creating a new cart entry, it should do an updateOrCreate() so that it either creates a new cart with that ID if one doesn't exist *OR* updates the existing one if it does.  Then the race condition goes away completely, no?  Because there's never a point where an empty cart is being returned.

**Comment by rrpadilla** [comment]
@nexxai Hi, added a content property to store the cart content. This will help to avoid race conditions.
See PR #119
