### ISSUE TITLE
cart instance destroyed after logout

### ISSUE THREAD

**Issue by SantoshiBhujel** [bumbummen99/LaravelShoppingcart#94]
cart instance is destroyed after the user logout though 'destroy_on_logout' => false in config cart.php

**Comment by bumbummen99** [comment]
This is due to a change in the default Laravel logout controller. It does always clear the session now so you will have to do some minor modifications to get it running. Basically you have to re write the cart into the session after logout.

Take a look here: 
https://github.com/bumbummen99/LaravelShoppingcartDemo/blob/48c46e8e363da6b23581b1af8af2b6f248159619/app/Http/Controllers/Auth/LoginController.php#L24  
https://github.com/bumbummen99/LaravelShoppingcartDemo/blob/48c46e8e363da6b23581b1af8af2b6f248159619/app/Http/Controllers/Auth/LoginController.php#L51

Tought this should be documented in the Readme, i am open for PR's :+1:
